((c++-mode  . ((tab-width . 4)
	       (c-basic-offset . 4)
	       (indent-tabs-mode . nil)))
 (c++-ts-mode . ((tab-width . 4)
		 (c-ts-mode-indent-offset . 4)
		 (indent-tabs-mode . nil)))
 (glsl-mode . ((tab-width . 4)
	       (c-basic-offset . 4)
	       (indent-tabs-mode . nil)))
 (hlsl-mode . ((tab-width . 4)
	       (c-basic-offset . 4)
	       (indent-tabs-mode . nil)))
 ( nil . ( (projectile-compilation-dir . "./build")))
 )
